apiVersion: v1
kind: Template
metadata:
  name: psql-cron
  annotations:
    description: "Deploys PostgreSQL Backup Cronjob"

parameters:
  - name: NAME
    description: "Name of the cronjob"
    value: "psql-cron"
  - name: SCHEDULE
    description: "Schedule for running the cronjob"
    value: "0/5 * * * *"
  - name: PGSQL_SERVICE
    description: "Which PostgreSQL service needs to be backed up."
    value: postgresql

  - name: PGSQL_SECRET
    description: "PostgreSQL Secret-file to use (usually same as PGSQL_SERVICE)"
    required: true
    value:
  - name: PGSQL_SECRET_USER_KEY
    description: "Key used in postgresql secret file for username"
    value: "common-pgsql-user"
  - name: PGSQL_SECRET_PASSWORD_KEY
    description: "Key used in postgresql secret file for password"
    value: "common-pgsql-password"

  - name: AWS_S3_BUCKET
    description: "s3 bucket for storing the backup file"
    required: true
    value:
  - name: AWS_SECRET
    description: "Name of the secret where authenication data is stored"
    required: true
    value: awsauth

  - name: NOTIFY_SLACK_ENABLED
    description: "Set to true if you want to use slack notifications"
    value: "false"
  - name: NOTIFY_EMAIL_ENABLED
    description: "Set to true if you want to use email notifications"
    value: "false"
  - name: NOTIFY_STDOUT_ENABLED
    description: "Logs errors to stdout"
    value: "true"
  - name: SLACK_API
    description: "URL to your Slack app."
    value: "CHANGEME"
  - name: DEBUG
    description: "Debugging mode"
    value: "false"

objects:
- apiVersion: batch/v1beta1
  kind: CronJob
  metadata:
    name: ${NAME}
  spec:
    schedule: ${SCHEDULE}
    jobTemplate:
      spec:
        template:
          metadata:
            labels:
              app: ${NAME}
          spec:
            containers:
            - name: ${NAME}
              image: registry.chp.npohosting.nl/backup-containers/psql-backup:latest
              imagePullPolicy: Always
              env:
              - name: NAME
                value: ${NAME}
              - name: STORAGE_METHOD
                value: s3
              - name: PGSQL_SERVICE
                value: ${PGSQL_SERVICE}
              - name: DEBUG
                value: ${DEBUG}
              - name: NOTIFY_SLACK_ENABLED
                value: ${NOTIFY_SLACK_ENABLED}
              - name: NOTIFY_EMAIL_ENABLED
                value: ${NOTIFY_EMAIL_ENABLED}
              - name: NOTIFY_STDOUT_ENABLED
                value: ${NOTIFY_STDOUT_ENABLED}
              - name: PGSQL_USER
                valueFrom:
                  secretKeyRef:
                    key: ${PGSQL_SECRET_USER_KEY}
                    name: ${PGSQL_SECRET}
              - name: PGPASSWORD
                valueFrom:
                  secretKeyRef:
                    key: ${PGSQL_SECRET_PASSWORD_KEY}
                    name: ${PGSQL_SECRET}
              - name: AWS_S3_BUCKET
                value: ${AWS_S3_BUCKET}
              - name: AWS_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    key: aws_access_key_id
                    name: ${AWS_SECRET}
              - name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    key: aws_secret_key_id
                    name: ${AWS_SECRET}
            restartPolicy: Never
